package zadaci_10_03_2017;

import java.io.IOException;

public class Zadatak4Test {
	public static void main(String[] args) throws Exception {

		// poziv main metode iz 3. zadatka i prosljedjivanje argumenta sa nazivom fajla
		
				String[] argumenti = { "Shihtzu.txt" };
				Zadatak4.main(argumenti);
					
	}
	}